# version: "3.8"

# services:
#   frontend:
#     build: .
#     container_name: frontend
#     ports:
#       - "80:80"
  
#   postgres:
#     image: postgres:15-alpine
#     container_name: postgres
#     restart: always
#     environment:
#       POSTGRES_DB: wiki
#       POSTGRES_USER: wikiuser
#       POSTGRES_PASSWORD: wikisecret
#     volumes:
#       - pgdata:/var/lib/postgresql/data

#   wikijs:
#     image: requarks/wiki:latest
#     container_name: wikijs
#     restart: always
#     depends_on:
#       - postgres
#     environment:
#       DB_TYPE: postgres
#       DB_HOST: postgres
#       DB_PORT: 5432
#       DB_USER: wikiuser
#       DB_PASS: wikisecret
#       DB_NAME: wiki
#     ports:
#       - "3000:3000"

# volumes:
#   pgdata:
version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikiuser
      POSTGRES_PASSWORD: wikisecret
    volumes:
      - pgdata:/var/lib/postgresql/data

  wikijs:
    image: requarks/wiki:latest
    container_name: wikijs
    restart: always
    depends_on:
      - postgres
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: wikiuser
      DB_PASS: wikisecret
      DB_NAME: wiki
    ports:
      - "3000:3000"

volumes:
  pgdata:
